name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stable-build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: install
        if: ${{ matrix.os.name != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: moon update

      - name: moon check
        run: moon check --deny-warn

      - name: moon info
        run: |
          moon info
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
      
      - name: moon test
        run: |
          moon test
          moon test --release
          